package com.example.util

import com.example.model.TextDrawElement
import com.example.model.TextDrawProject

object PawnCodeGenerator {

    /**
     * Generates a complete, production-ready Pawn (.pwn) script.
     */
    fun generatePawnScript(project: TextDrawProject, elements: List<TextDrawElement>): String {
        val sb = StringBuilder()
        val isPlayer = project.isPlayerTextDraw
        val prefix = if (isPlayer) "PlayerTextDraw" else "TextDraw"
        val varType = if (isPlayer) "PlayerText:" else "Text:"

        sb.append("// ===========================================================\n")
        sb.append("// Generated by SA-MP TD Studio for Android\n")
        sb.append("// Project: ${project.name}\n")
        sb.append("// Total Elements: ${elements.size}\n")
        sb.append("// Type: ${if (isPlayer) "Player TextDraw" else "Global TextDraw"}\n")
        sb.append("// ===========================================================\n\n")

        sb.append("#include <a_samp>\n\n")

        // Variable definitions
        sb.append("// Variable Declarations\n")
        if (isPlayer) {
            elements.forEach { el ->
                sb.append("new $varType${el.varName}[MAX_PLAYERS] = {PlayerText:INVALID_TEXT_DRAW, ...};\n")
            }
        } else {
            elements.forEach { el ->
                sb.append("new $varType${el.varName} = Text:INVALID_TEXT_DRAW;\n")
            }
        }
        sb.append("\n")

        // Creation function
        val funcName = if (isPlayer) "CreatePlayerTextDraws(playerid)" else "CreateGlobalTextDraws()"
        sb.append("// Call this function to initialize the TextDraws\n")
        sb.append("stock $funcName\n{\n")

        elements.forEach { el ->
            val varRef = if (isPlayer) "${el.varName}[playerid]" else el.varName
            val pIdParam = if (isPlayer) "playerid, " else ""
            val escapedText = el.text.replace("\"", "\\\"").replace("\n", "~n~")

            sb.append("    // --- ${el.varName} ---\n")
            sb.append("    $varRef = ${if (isPlayer) "CreatePlayerTextDraw" else "TextDrawCreate"}(${pIdParam}%.3ff, %.3ff, \"$escapedText\");\n".format(el.posX, el.posY))
            sb.append("    ${prefix}LetterSize(${pIdParam}$varRef, %.4ff, %.4ff);\n".format(el.letterSizeX, el.letterSizeY))
            sb.append("    ${prefix}TextSize(${pIdParam}$varRef, %.3ff, %.3ff);\n".format(el.textSizeX, el.textSizeY))
            sb.append("    ${prefix}Alignment(${pIdParam}$varRef, ${el.alignment});\n")
            sb.append("    ${prefix}Color(${pIdParam}$varRef, ${SampColorUtils.formatToSampPawnHex(el.color)});\n")
            sb.append("    ${prefix}UseBox(${pIdParam}$varRef, ${if (el.useBox) 1 else 0});\n")
            if (el.useBox) {
                sb.append("    ${prefix}BoxColor(${pIdParam}$varRef, ${SampColorUtils.formatToSampPawnHex(el.boxColor)});\n")
            }
            sb.append("    ${prefix}SetShadow(${pIdParam}$varRef, ${el.shadow});\n")
            sb.append("    ${prefix}SetOutline(${pIdParam}$varRef, ${el.outline});\n")
            sb.append("    ${prefix}BackgroundColor(${pIdParam}$varRef, ${SampColorUtils.formatToSampPawnHex(el.backgroundColor)});\n")
            sb.append("    ${prefix}Font(${pIdParam}$varRef, ${el.font});\n")
            sb.append("    ${prefix}SetProportional(${pIdParam}$varRef, ${if (el.proportional) 1 else 0});\n")
            sb.append("    ${prefix}SetSelectable(${pIdParam}$varRef, ${if (el.selectable) 1 else 0});\n")

            if (el.font == 5 && el.modelId > 0) {
                sb.append("    ${prefix}SetPreviewModel(${pIdParam}$varRef, ${el.modelId});\n")
                sb.append("    ${prefix}SetPreviewRot(${pIdParam}$varRef, %.2ff, %.2ff, %.2ff, %.2ff);\n".format(el.modelRotX, el.modelRotY, el.modelRotZ, el.modelZoom))
            }
            sb.append("\n")
        }
        sb.append("    return 1;\n}\n\n")

        // Show function
        val showFuncName = if (isPlayer) "ShowPlayerTextDraws(playerid)" else "ShowGlobalTextDraws(playerid)"
        sb.append("// Call this to show the TextDraws to a player\n")
        sb.append("stock $showFuncName\n{\n")
        elements.forEach { el ->
            val varRef = if (isPlayer) "${el.varName}[playerid]" else el.varName
            if (isPlayer) {
                sb.append("    PlayerTextDrawShow(playerid, $varRef);\n")
            } else {
                sb.append("    TextDrawShowForPlayer(playerid, $varRef);\n")
            }
        }
        sb.append("    return 1;\n}\n\n")

        // Hide function
        val hideFuncName = if (isPlayer) "HidePlayerTextDraws(playerid)" else "HideGlobalTextDraws(playerid)"
        sb.append("// Call this to hide the TextDraws from a player\n")
        sb.append("stock $hideFuncName\n{\n")
        elements.forEach { el ->
            val varRef = if (isPlayer) "${el.varName}[playerid]" else el.varName
            if (isPlayer) {
                sb.append("    PlayerTextDrawHide(playerid, $varRef);\n")
            } else {
                sb.append("    TextDrawHideForPlayer(playerid, $varRef);\n")
            }
        }
        sb.append("    return 1;\n}\n\n")

        // Destroy function
        val destroyFuncName = if (isPlayer) "DestroyPlayerTextDraws(playerid)" else "DestroyGlobalTextDraws()"
        sb.append("// Call this when destroying TextDraws (e.g. OnPlayerDisconnect or OnGameModeExit)\n")
        sb.append("stock $destroyFuncName\n{\n")
        elements.forEach { el ->
            val varRef = if (isPlayer) "${el.varName}[playerid]" else el.varName
            if (isPlayer) {
                sb.append("    if ($varRef != PlayerText:INVALID_TEXT_DRAW) {\n")
                sb.append("        PlayerTextDrawDestroy(playerid, $varRef);\n")
                sb.append("        $varRef = PlayerText:INVALID_TEXT_DRAW;\n")
                sb.append("    }\n")
            } else {
                sb.append("    if ($varRef != Text:INVALID_TEXT_DRAW) {\n")
                sb.append("        TextDrawDestroy($varRef);\n")
                sb.append("        $varRef = Text:INVALID_TEXT_DRAW;\n")
                sb.append("    }\n")
            }
        }
        sb.append("    return 1;\n}\n")

        return sb.toString()
    }
}
